using System.Net.Mail;
using AveroNova.App.UI.Data;
using AveroNova.App.UI.Models;
using AveroNova.App.UI.Services.Interfaces;
using AveroNova.Domain.Enums;
using Microsoft.EntityFrameworkCore;

namespace AveroNova.App.UI.Services;

public sealed class LocalUserService:IUserService
{
 private static readonly PermissionModel[] Catalog=[new(){Key="dashboard.view",Module="Dashboard",Label="View Dashboard"},new(){Key="billing.view",Module="Billing",Label="View Invoices"},new(){Key="billing.create",Module="Billing",Label="Create Invoices"},new(){Key="customers.manage",Module="Customers",Label="Manage Customers"},new(){Key="products.manage",Module="Products",Label="Manage Products"},new(){Key="inventory.manage",Module="Inventory",Label="Manage Inventory"},new(){Key="purchases.manage",Module="Purchases",Label="Manage Purchases"},new(){Key="expenses.manage",Module="Expenses",Label="Manage Expenses"},new(){Key="returns.manage",Module="Returns",Label="Manage Returns"},new(){Key="reports.view",Module="Reports",Label="View Reports"},new(){Key="users.manage",Module="Administration",Label="Manage Users"},new(){Key="settings.manage",Module="Settings",Label="Manage Settings"}];
 private readonly IDbContextFactory<LocalAppDbContext> _factory;private readonly IAppSessionContext _session;
 public LocalUserService(IDbContextFactory<LocalAppDbContext> factory,IAppSessionContext session){_factory=factory;_session=session;}
 public async Task<List<UserModel>> GetAllAsync(Guid companyId){if(!Allows(companyId))return[];await using var db=await _factory.CreateDbContextAsync();var memberships=await db.UserCompanies.AsNoTracking().Where(x=>x.CompanyId==companyId).ToListAsync();var ids=memberships.Select(x=>x.UserId).ToList();var users=await db.Users.AsNoTracking().Where(x=>ids.Contains(x.Id)).ToListAsync();var roles=await db.CompanyRoles.AsNoTracking().Where(x=>x.CompanyId==companyId).ToDictionaryAsync(x=>x.Id);return users.Select(u=>Map(u,memberships.Single(m=>m.UserId==u.Id),roles)).OrderBy(x=>x.Name).ToList();}
 public async Task<UserModel?> GetByIdAsync(Guid id){if(_session.CurrentCompanyId is not Guid cid)return null;return(await GetAllAsync(cid)).FirstOrDefault(x=>x.LocalId==id);}
 public async Task<(bool Ok,string? Error)> CreateAsync(UserModel m){var err=await ValidateUserAsync(m);if(err is not null)return(false,err);await using var db=await _factory.CreateDbContextAsync();var email=m.Email.Trim().ToLowerInvariant();if(await db.Users.AnyAsync(x=>x.Email.ToLower()==email))return(false,"A user with this email already exists.");var now=DateTime.UtcNow;m.LocalId=m.LocalId==Guid.Empty?Guid.NewGuid():m.LocalId;var user=new LocalUserEntity{Id=m.LocalId,FullName=m.Name.Trim(),Email=email,MobileNumber=m.Phone.Trim(),IsActive=m.Status==UserStatus.Active,AdminStatus=(int)m.Status,Notes=m.Notes.Trim(),SyncVersion=1};var membership=new LocalUserCompanyEntity{Id=Guid.NewGuid(),UserId=user.Id,CompanyId=m.CompanyId!.Value,RoleId=m.RoleId,IsActive=true};db.Users.Add(user);db.UserCompanies.Add(membership);LocalSyncQueueWriter.Enqueue(db,"CompanyUser",user.Id,m.CompanyId.Value,SyncOperation.Create,Payload(user,membership),now);await db.SaveChangesAsync();return(true,null);}
 public async Task<(bool Ok,string? Error)> UpdateAsync(UserModel m){var err=await ValidateUserAsync(m);if(err is not null)return(false,err);await using var db=await _factory.CreateDbContextAsync();var cid=m.CompanyId!.Value;var member=await db.UserCompanies.FirstOrDefaultAsync(x=>x.CompanyId==cid&&x.UserId==m.LocalId);var user=await db.Users.FirstOrDefaultAsync(x=>x.Id==m.LocalId);if(user is null||member is null||!Allows(cid))return(false,"User not found.");var email=m.Email.Trim().ToLowerInvariant();if(await db.Users.AnyAsync(x=>x.Id!=m.LocalId&&x.Email.ToLower()==email))return(false,"A user with this email already exists.");user.FullName=m.Name.Trim();user.Email=email;user.MobileNumber=m.Phone.Trim();user.IsActive=m.Status==UserStatus.Active;user.AdminStatus=(int)m.Status;user.Notes=m.Notes.Trim();user.SyncVersion++;member.RoleId=m.RoleId;member.IsActive=m.Status==UserStatus.Active;LocalSyncQueueWriter.Enqueue(db,"CompanyUser",user.Id,cid,SyncOperation.Update,Payload(user,member),DateTime.UtcNow);await db.SaveChangesAsync();return(true,null);}
 public async Task<(bool Ok,string? Error)> DeleteAsync(Guid id){if(_session.CurrentCompanyId is not Guid cid)return(false,"No active company.");if(_session.CurrentUserId==id)return(false,"You cannot delete your own account.");await using var db=await _factory.CreateDbContextAsync();var member=await db.UserCompanies.FirstOrDefaultAsync(x=>x.CompanyId==cid&&x.UserId==id);if(member is null)return(false,"User not found.");if(member.IsOwner)return(false,"Company owner cannot be deleted.");db.UserCompanies.Remove(member);LocalSyncQueueWriter.Enqueue(db,"CompanyUser",id,cid,SyncOperation.Delete,new{UserId=id,CompanyId=cid},DateTime.UtcNow);await db.SaveChangesAsync();return(true,null);}
 public Task<(bool Ok,string? Error)> ActivateAsync(Guid id)=>SetStatusAsync(id,UserStatus.Active);public Task<(bool Ok,string? Error)> DeactivateAsync(Guid id)=>SetStatusAsync(id,UserStatus.Inactive);
 private async Task<(bool Ok,string? Error)> SetStatusAsync(Guid id,UserStatus status){var m=await GetByIdAsync(id);if(m is null)return(false,"User not found.");m.Status=status;return await UpdateAsync(m);}
 public async Task<(bool Ok,string? Error)> ResetPasswordAsync(Guid id){if(_session.CurrentCompanyId is not Guid cid||!Allows(cid))return(false,"No active company.");await using var db=await _factory.CreateDbContextAsync();if(!await db.UserCompanies.AnyAsync(x=>x.CompanyId==cid&&x.UserId==id))return(false,"User not found.");LocalSyncQueueWriter.Enqueue(db,"UserPasswordReset",id,cid,SyncOperation.Update,new{UserId=id,CompanyId=cid},DateTime.UtcNow);await db.SaveChangesAsync();return(true,"Password reset request queued for secure processing.");}
 public async Task<List<RoleModel>> GetRolesAsync(Guid companyId){if(!Allows(companyId))return[];await using var db=await _factory.CreateDbContextAsync();var roles=await db.CompanyRoles.AsNoTracking().Where(x=>x.CompanyId==companyId).OrderBy(x=>x.Name).ToListAsync();var permissions=await db.CompanyRolePermissions.AsNoTracking().Where(x=>x.CompanyId==companyId).ToListAsync();var counts=await db.UserCompanies.AsNoTracking().Where(x=>x.CompanyId==companyId&&x.RoleId!=null).GroupBy(x=>x.RoleId).Select(g=>new{Id=g.Key,Count=g.Count()}).ToDictionaryAsync(x=>x.Id,x=>x.Count);return roles.Select(x=>new RoleModel{LocalId=x.Id,ServerId=x.ServerId?.ToString("D"),CompanyId=x.CompanyId,Name=x.Name,Description=x.Description,IsSystem=x.IsSystem,Permissions=permissions.Where(p=>p.RoleId==x.Id).Select(p=>p.PermissionKey).ToList(),UserCount=counts.GetValueOrDefault(x.Id),SyncStatus=ToUi(x.SyncStatus),CreatedAt=x.CreatedAtUtc,UpdatedAt=x.UpdatedAtUtc,LastSyncedAt=x.LastSyncedAtUtc}).ToList();}
 public async Task<RoleModel?> GetRoleByIdAsync(Guid id){if(_session.CurrentCompanyId is not Guid cid)return null;return(await GetRolesAsync(cid)).FirstOrDefault(x=>x.LocalId==id);}
 public Task<List<RoleModel>> GetAllRolesAsync()=>_session.CurrentCompanyId is Guid cid?GetRolesAsync(cid):Task.FromResult<List<RoleModel>>([]);
 public async Task<(bool Ok,string? Error)> CreateRoleAsync(RoleModel role){if(_session.CurrentCompanyId is not Guid cid)return(false,"No active company.");role.CompanyId=cid;var err=ValidateRole(role);if(err is not null)return(false,err);await using var db=await _factory.CreateDbContextAsync();if(await db.CompanyRoles.AnyAsync(x=>x.CompanyId==cid&&x.Name.ToLower()==role.Name.Trim().ToLower()))return(false,"Role name already exists.");var now=DateTime.UtcNow;role.LocalId=role.LocalId==Guid.Empty?Guid.NewGuid():role.LocalId;var x=new LocalCompanyRoleEntity{Id=role.LocalId,CompanyId=cid,Name=role.Name.Trim(),Description=role.Description.Trim(),IsSystem=false,SyncStatus=(int)RecordSyncStatus.Pending,CreatedAtUtc=now,UpdatedAtUtc=now};db.CompanyRoles.Add(x);AddPermissions(db,role,cid);LocalSyncQueueWriter.Enqueue(db,"Role",x.Id,cid,SyncOperation.Create,RolePayload(x,role.Permissions),now);await db.SaveChangesAsync();return(true,null);}
 public async Task<(bool Ok,string? Error)> UpdateRoleAsync(RoleModel role){if(_session.CurrentCompanyId is not Guid cid)return(false,"No active company.");role.CompanyId=cid;var err=ValidateRole(role);if(err is not null)return(false,err);await using var db=await _factory.CreateDbContextAsync();var x=await db.CompanyRoles.FirstOrDefaultAsync(r=>r.Id==role.LocalId&&r.CompanyId==cid);if(x is null)return(false,"Role not found.");if(x.IsSystem&&x.Name!=role.Name.Trim())return(false,"System role name cannot be changed.");if(await db.CompanyRoles.AnyAsync(r=>r.CompanyId==cid&&r.Id!=x.Id&&r.Name.ToLower()==role.Name.Trim().ToLower()))return(false,"Role name already exists.");x.Name=role.Name.Trim();x.Description=role.Description.Trim();x.SyncStatus=(int)RecordSyncStatus.Pending;x.UpdatedAtUtc=DateTime.UtcNow;db.CompanyRolePermissions.RemoveRange(db.CompanyRolePermissions.Where(p=>p.CompanyId==cid&&p.RoleId==x.Id));AddPermissions(db,role,cid);LocalSyncQueueWriter.Enqueue(db,"Role",x.Id,cid,SyncOperation.Update,RolePayload(x,role.Permissions),x.UpdatedAtUtc);await db.SaveChangesAsync();return(true,null);}
 public async Task<(bool Ok,string? Error)> DeleteRoleAsync(Guid id){if(_session.CurrentCompanyId is not Guid cid)return(false,"No active company.");await using var db=await _factory.CreateDbContextAsync();var x=await db.CompanyRoles.FirstOrDefaultAsync(r=>r.Id==id&&r.CompanyId==cid);if(x is null)return(false,"Role not found.");if(x.IsSystem)return(false,"System roles cannot be deleted.");if(await db.UserCompanies.AnyAsync(u=>u.CompanyId==cid&&u.RoleId==id))return(false,"Role is assigned to users.");db.CompanyRolePermissions.RemoveRange(db.CompanyRolePermissions.Where(p=>p.CompanyId==cid&&p.RoleId==id));db.CompanyRoles.Remove(x);LocalSyncQueueWriter.Enqueue(db,"Role",id,cid,SyncOperation.Delete,new{x.Id,x.CompanyId},DateTime.UtcNow);await db.SaveChangesAsync();return(true,null);}
 public Task<List<PermissionModel>> GetPermissionsAsync()=>Task.FromResult(Catalog.Select(x=>new PermissionModel{Key=x.Key,Module=x.Module,Label=x.Label,Description=x.Description}).ToList());
 private async Task<string?> ValidateUserAsync(UserModel m){if(m.CompanyId is not Guid cid||!Allows(cid))return"You do not have access to this company.";if(string.IsNullOrWhiteSpace(m.Name))return"Full name is required.";if(string.IsNullOrWhiteSpace(m.Email))return"Email is required.";try{_=new MailAddress(m.Email.Trim());}catch{return"Enter a valid email.";}if(m.RoleId is null)return"Select a role.";await using var db=await _factory.CreateDbContextAsync();return await db.CompanyRoles.AnyAsync(x=>x.Id==m.RoleId&&x.CompanyId==cid)?null:"Role not found for this company.";}
 private string? ValidateRole(RoleModel r){if(!Allows(r.CompanyId))return"You do not have access to this company.";if(string.IsNullOrWhiteSpace(r.Name))return"Role name is required.";if(r.Name.Trim().Length>100)return"Role name must be 100 characters or fewer.";if(r.Permissions.Any(p=>Catalog.All(c=>c.Key!=p)))return"Role contains an unknown permission.";return null;}
 private static void AddPermissions(LocalAppDbContext db,RoleModel r,Guid cid){foreach(var key in r.Permissions.Distinct())db.CompanyRolePermissions.Add(new LocalCompanyRolePermissionEntity{Id=Guid.NewGuid(),CompanyId=cid,RoleId=r.LocalId,PermissionKey=key});}
 private bool Allows(Guid id)=>id!=Guid.Empty&&_session.CurrentCompanyId==id;
 private static UserModel Map(LocalUserEntity u,LocalUserCompanyEntity m,IReadOnlyDictionary<Guid,LocalCompanyRoleEntity> roles){var role=m.RoleId is Guid rid&&roles.TryGetValue(rid,out var r)?r:null;return new UserModel{LocalId=u.Id,CompanyId=m.CompanyId,Name=u.FullName,Email=u.Email,Phone=u.MobileNumber,Status=(UserStatus)u.AdminStatus,RoleId=m.RoleId,Role=role?.Name??"Unassigned",Notes=u.Notes,LastLoginAt=u.LastLoginAtUtc,AvatarInitials=string.Join("",u.FullName.Split(' ',StringSplitOptions.RemoveEmptyEntries).Take(2).Select(x=>char.ToUpperInvariant(x[0])))};}
 private static object Payload(LocalUserEntity u,LocalUserCompanyEntity m)=>new{u.Id,m.CompanyId,u.FullName,u.Email,u.MobileNumber,u.IsActive,u.AdminStatus,u.Notes,m.RoleId};private static object RolePayload(LocalCompanyRoleEntity x,List<string> p)=>new{x.Id,x.CompanyId,x.Name,x.Description,x.IsSystem,Permissions=p};private static SyncStatus ToUi(int s)=>(RecordSyncStatus)s==RecordSyncStatus.Synced?SyncStatus.Synced:(RecordSyncStatus)s==RecordSyncStatus.Failed?SyncStatus.SyncFailed:SyncStatus.PendingSync;
}
