using System.Text.Json;
using AveroNova.App.UI.Data;
using AveroNova.App.UI.Models;
using AveroNova.App.UI.Services.Interfaces;
using AveroNova.Domain.Enums;
using Microsoft.EntityFrameworkCore;

namespace AveroNova.App.UI.Services;

public sealed class LocalReturnService : IReturnService
{
    private readonly IDbContextFactory<LocalAppDbContext> _factory;
    private readonly IAppSessionContext _session;
    private readonly IConnectivityService _connectivity;
    private readonly IReturnSyncService _sync;

    public LocalReturnService(IDbContextFactory<LocalAppDbContext> factory, IAppSessionContext session, IConnectivityService connectivity, IReturnSyncService sync)
    { _factory=factory; _session=session; _connectivity=connectivity; _sync=sync; }

    public async Task<List<SalesReturnModel>> GetSalesReturnsAsync(Guid companyId){if(!Allows(companyId))return[];await using var db=await _factory.CreateDbContextAsync();return(await db.SalesReturns.AsNoTracking().Where(x=>x.CompanyId==companyId).OrderByDescending(x=>x.ReturnDate).ToListAsync()).Select(MapSales).ToList();}
    public async Task<SalesReturnModel?> GetSalesReturnByIdAsync(Guid id){await using var db=await _factory.CreateDbContextAsync();var x=await db.SalesReturns.AsNoTracking().FirstOrDefaultAsync(r=>r.Id==id);return x is null||!Allows(x.CompanyId)?null:MapSales(x);}
    public async Task<(bool Ok,string? Error)> CreateSalesReturnAsync(SalesReturnModel m){var err=await ValidateSalesAsync(m);if(err is not null)return(false,err);await using var db=await _factory.CreateDbContextAsync();await LocalSyncVersionStore.EnsureSchemaAsync(db);var now=DateTime.UtcNow;m.LocalId=m.LocalId==Guid.Empty?Guid.NewGuid():m.LocalId;m.ReturnNumber=await NextAsync(db,"SR",m.CompanyId,true);var x=SalesEntity(m,now);db.SalesReturns.Add(x);LocalSyncQueueWriter.Enqueue(db,"SalesReturn",x.Id,x.CompanyId,SyncOperation.Create,SalesPayload(x,1),now);await db.SaveChangesAsync();AfterQueued();return(true,null);}
    public async Task<(bool Ok,string? Error)> UpdateSalesReturnAsync(SalesReturnModel m){var err=await ValidateSalesAsync(m);if(err is not null)return(false,err);await using var db=await _factory.CreateDbContextAsync();await LocalSyncVersionStore.EnsureSchemaAsync(db);var x=await db.SalesReturns.FirstOrDefaultAsync(r=>r.Id==m.LocalId);if(x is null||!Allows(x.CompanyId)||x.CompanyId!=m.CompanyId)return(false,"Sales return not found.");var version=await LocalSyncVersionStore.GetSalesReturnAsync(db,x.Id);Apply(x,m,DateTime.UtcNow);LocalSyncQueueWriter.Enqueue(db,"SalesReturn",x.Id,x.CompanyId,SyncOperation.Update,SalesPayload(x,version),x.UpdatedAtUtc);await db.SaveChangesAsync();AfterQueued();return(true,null);}
    public async Task<(bool Ok,string? Error)> DeleteSalesReturnAsync(Guid id){await using var db=await _factory.CreateDbContextAsync();var x=await db.SalesReturns.FirstOrDefaultAsync(r=>r.Id==id);if(x is null||!Allows(x.CompanyId))return(false,"Sales return not found.");db.SalesReturns.Remove(x);LocalSyncQueueWriter.Enqueue(db,"SalesReturn",x.Id,x.CompanyId,SyncOperation.Delete,new{x.Id,x.CompanyId},DateTime.UtcNow);await db.SaveChangesAsync();AfterQueued();return(true,null);}

    public async Task<List<PurchaseReturnModel>> GetPurchaseReturnsAsync(Guid companyId){if(!Allows(companyId))return[];await using var db=await _factory.CreateDbContextAsync();return(await db.PurchaseReturns.AsNoTracking().Where(x=>x.CompanyId==companyId).OrderByDescending(x=>x.ReturnDate).ToListAsync()).Select(MapPurchase).ToList();}
    public async Task<PurchaseReturnModel?> GetPurchaseReturnByIdAsync(Guid id){await using var db=await _factory.CreateDbContextAsync();var x=await db.PurchaseReturns.AsNoTracking().FirstOrDefaultAsync(r=>r.Id==id);return x is null||!Allows(x.CompanyId)?null:MapPurchase(x);}
    public async Task<(bool Ok,string? Error)> CreatePurchaseReturnAsync(PurchaseReturnModel m){var err=await ValidatePurchaseAsync(m);if(err is not null)return(false,err);await using var db=await _factory.CreateDbContextAsync();await LocalSyncVersionStore.EnsureSchemaAsync(db);var now=DateTime.UtcNow;m.LocalId=m.LocalId==Guid.Empty?Guid.NewGuid():m.LocalId;m.ReturnNumber=await NextAsync(db,"PR",m.CompanyId,false);var x=PurchaseEntity(m,now);db.PurchaseReturns.Add(x);LocalSyncQueueWriter.Enqueue(db,"PurchaseReturn",x.Id,x.CompanyId,SyncOperation.Create,PurchasePayload(x,1),now);await db.SaveChangesAsync();AfterQueued();return(true,null);}
    public async Task<(bool Ok,string? Error)> UpdatePurchaseReturnAsync(PurchaseReturnModel m){var err=await ValidatePurchaseAsync(m);if(err is not null)return(false,err);await using var db=await _factory.CreateDbContextAsync();await LocalSyncVersionStore.EnsureSchemaAsync(db);var x=await db.PurchaseReturns.FirstOrDefaultAsync(r=>r.Id==m.LocalId);if(x is null||!Allows(x.CompanyId)||x.CompanyId!=m.CompanyId)return(false,"Purchase return not found.");var version=await LocalSyncVersionStore.GetPurchaseReturnAsync(db,x.Id);Apply(x,m,DateTime.UtcNow);LocalSyncQueueWriter.Enqueue(db,"PurchaseReturn",x.Id,x.CompanyId,SyncOperation.Update,PurchasePayload(x,version),x.UpdatedAtUtc);await db.SaveChangesAsync();AfterQueued();return(true,null);}
    public async Task<(bool Ok,string? Error)> DeletePurchaseReturnAsync(Guid id){await using var db=await _factory.CreateDbContextAsync();var x=await db.PurchaseReturns.FirstOrDefaultAsync(r=>r.Id==id);if(x is null||!Allows(x.CompanyId))return(false,"Purchase return not found.");db.PurchaseReturns.Remove(x);LocalSyncQueueWriter.Enqueue(db,"PurchaseReturn",x.Id,x.CompanyId,SyncOperation.Delete,new{x.Id,x.CompanyId},DateTime.UtcNow);await db.SaveChangesAsync();AfterQueued();return(true,null);}

    private void AfterQueued(){_connectivity.IncrementPending();if(_connectivity.IsOnline)_=_sync.SyncPendingAsync();}
    private async Task<string?> ValidateSalesAsync(SalesReturnModel m){var common=Validate(m.CompanyId,m.ReturnDate,m.Reason,m.RefundAmount);if(common is not null)return common;if(m.InvoiceId==Guid.Empty)return"Select an invoice.";await using var db=await _factory.CreateDbContextAsync();var invoice=await db.Invoices.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==m.InvoiceId&&x.CompanyId==m.CompanyId);if(invoice is null)return"Invoice not found for this company.";var items=JsonSerializer.Deserialize<List<InvoiceLineItem>>(invoice.ItemsJson)??[];var total=items.Sum(x=>x.GrandTotal);if(m.RefundAmount>total)return"Refund cannot exceed invoice total.";m.InvoiceNumber=invoice.InvoiceNumber;m.CustomerId=invoice.CustomerId;m.CustomerName=invoice.CustomerName;return null;}
    private async Task<string?> ValidatePurchaseAsync(PurchaseReturnModel m){var common=Validate(m.CompanyId,m.ReturnDate,m.Reason,m.RefundAmount);if(common is not null)return common;if(m.PurchaseId==Guid.Empty)return"Select a purchase.";await using var db=await _factory.CreateDbContextAsync();var purchase=await db.Purchases.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==m.PurchaseId&&x.CompanyId==m.CompanyId);if(purchase is null)return"Purchase not found for this company.";var items=JsonSerializer.Deserialize<List<PurchaseLineItem>>(purchase.ItemsJson)??[];var total=items.Sum(x=>x.GrandTotal);if(m.RefundAmount>total)return"Refund cannot exceed purchase total.";m.PurchaseNumber=purchase.PurchaseNumber;m.SupplierId=purchase.SupplierId;m.SupplierName=purchase.SupplierName;return null;}
    private string? Validate(Guid companyId,DateTime date,string reason,decimal refund){if(!Allows(companyId))return"You do not have access to this company.";if(date.Date>DateTime.Today)return"Return date cannot be in the future.";if(string.IsNullOrWhiteSpace(reason))return"Return reason is required.";if(refund<=0)return"Refund amount must be greater than zero.";return null;}
    private async Task<string> NextAsync(LocalAppDbContext db,string kind,Guid cid,bool sales){var prefix=$"{kind}-{DateTime.Today:yyyy}-";var values=sales?await db.SalesReturns.Where(x=>x.CompanyId==cid&&x.ReturnNumber.StartsWith(prefix)).Select(x=>x.ReturnNumber).ToListAsync():await db.PurchaseReturns.Where(x=>x.CompanyId==cid&&x.ReturnNumber.StartsWith(prefix)).Select(x=>x.ReturnNumber).ToListAsync();var max=values.Select(x=>int.TryParse(x[prefix.Length..],out var n)?n:0).DefaultIfEmpty().Max();return$"{prefix}{max+1:D4}";}
    private bool Allows(Guid id)=>id!=Guid.Empty&&_session.CurrentCompanyId==id;
    private static SalesReturnModel MapSales(LocalSalesReturnEntity x)=>new(){LocalId=x.Id,ServerId=x.ServerId?.ToString("D"),CompanyId=x.CompanyId,ReturnNumber=x.ReturnNumber,InvoiceId=x.InvoiceId,InvoiceNumber=x.InvoiceNumber,CustomerId=x.CustomerId,CustomerName=x.CustomerName,ReturnDate=x.ReturnDate,Items=JsonSerializer.Deserialize<List<ReturnLineItem>>(x.ItemsJson)??[],Reason=x.Reason,Notes=x.Notes,RefundAmount=x.RefundAmount,Status=(ReturnStatus)x.Status,SyncStatus=ToUi(x.SyncStatus),CreatedAt=x.CreatedAtUtc,UpdatedAt=x.UpdatedAtUtc,LastSyncedAt=x.LastSyncedAtUtc};
    private static PurchaseReturnModel MapPurchase(LocalPurchaseReturnEntity x)=>new(){LocalId=x.Id,ServerId=x.ServerId?.ToString("D"),CompanyId=x.CompanyId,ReturnNumber=x.ReturnNumber,PurchaseId=x.PurchaseId,PurchaseNumber=x.PurchaseNumber,SupplierId=x.SupplierId,SupplierName=x.SupplierName,ReturnDate=x.ReturnDate,Items=JsonSerializer.Deserialize<List<ReturnLineItem>>(x.ItemsJson)??[],Reason=x.Reason,Notes=x.Notes,RefundAmount=x.RefundAmount,Status=(ReturnStatus)x.Status,SyncStatus=ToUi(x.SyncStatus),CreatedAt=x.CreatedAtUtc,UpdatedAt=x.UpdatedAtUtc,LastSyncedAt=x.LastSyncedAtUtc};
    private static LocalSalesReturnEntity SalesEntity(SalesReturnModel m,DateTime n)=>new(){Id=m.LocalId,CompanyId=m.CompanyId,ReturnNumber=m.ReturnNumber,InvoiceId=m.InvoiceId,InvoiceNumber=m.InvoiceNumber,CustomerId=m.CustomerId,CustomerName=m.CustomerName,ReturnDate=m.ReturnDate.Date,ItemsJson=JsonSerializer.Serialize(m.Items),Reason=m.Reason.Trim(),Notes=m.Notes.Trim(),RefundAmount=m.RefundAmount,Status=(int)m.Status,SyncStatus=(int)RecordSyncStatus.Pending,CreatedAtUtc=n,UpdatedAtUtc=n};
    private static LocalPurchaseReturnEntity PurchaseEntity(PurchaseReturnModel m,DateTime n)=>new(){Id=m.LocalId,CompanyId=m.CompanyId,ReturnNumber=m.ReturnNumber,PurchaseId=m.PurchaseId,PurchaseNumber=m.PurchaseNumber,SupplierId=m.SupplierId,SupplierName=m.SupplierName,ReturnDate=m.ReturnDate.Date,ItemsJson=JsonSerializer.Serialize(m.Items),Reason=m.Reason.Trim(),Notes=m.Notes.Trim(),RefundAmount=m.RefundAmount,Status=(int)m.Status,SyncStatus=(int)RecordSyncStatus.Pending,CreatedAtUtc=n,UpdatedAtUtc=n};
    private static void Apply(LocalSalesReturnEntity x,SalesReturnModel m,DateTime n){x.InvoiceId=m.InvoiceId;x.InvoiceNumber=m.InvoiceNumber;x.CustomerId=m.CustomerId;x.CustomerName=m.CustomerName;x.ReturnDate=m.ReturnDate.Date;x.ItemsJson=JsonSerializer.Serialize(m.Items);x.Reason=m.Reason.Trim();x.Notes=m.Notes.Trim();x.RefundAmount=m.RefundAmount;x.Status=(int)m.Status;x.SyncStatus=(int)RecordSyncStatus.Pending;x.UpdatedAtUtc=n;x.SyncError=null;}
    private static void Apply(LocalPurchaseReturnEntity x,PurchaseReturnModel m,DateTime n){x.PurchaseId=m.PurchaseId;x.PurchaseNumber=m.PurchaseNumber;x.SupplierId=m.SupplierId;x.SupplierName=m.SupplierName;x.ReturnDate=m.ReturnDate.Date;x.ItemsJson=JsonSerializer.Serialize(m.Items);x.Reason=m.Reason.Trim();x.Notes=m.Notes.Trim();x.RefundAmount=m.RefundAmount;x.Status=(int)m.Status;x.SyncStatus=(int)RecordSyncStatus.Pending;x.UpdatedAtUtc=n;x.SyncError=null;}
    private static object SalesPayload(LocalSalesReturnEntity x,long syncVersion)=>new{x.Id,x.CompanyId,x.ReturnNumber,x.InvoiceId,x.InvoiceNumber,x.CustomerId,x.CustomerName,x.ReturnDate,x.ItemsJson,x.Reason,x.Notes,x.RefundAmount,x.Status,SyncVersion=Math.Max(1L,syncVersion)};
    private static object PurchasePayload(LocalPurchaseReturnEntity x,long syncVersion)=>new{x.Id,x.CompanyId,x.ReturnNumber,x.PurchaseId,x.PurchaseNumber,x.SupplierId,x.SupplierName,x.ReturnDate,x.ItemsJson,x.Reason,x.Notes,x.RefundAmount,x.Status,SyncVersion=Math.Max(1L,syncVersion)};
    private static SyncStatus ToUi(int s)=>(RecordSyncStatus)s==RecordSyncStatus.Synced?SyncStatus.Synced:(RecordSyncStatus)s==RecordSyncStatus.Failed?SyncStatus.SyncFailed:SyncStatus.PendingSync;
}
