using System.Security.Claims;
using AveroNova.Application.Common;
using AveroNova.Application.DTOs.Auth;
using AveroNova.Application.Interfaces.Auth;
using AveroNova.Application.Interfaces.Security;
using AveroNova.Domain.Constants;
using AveroNova.Domain.Entities;
using AveroNova.Domain.Enums;
using AveroNova.Infrastructure.Persistence;
using AveroNova.Shared.Security;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace AveroNova.Infrastructure.Auth;

public sealed class AuthService : IAuthService
{
    private readonly AppDbContext _db;
    private readonly IPasswordHasher _passwordHasher;
    private readonly IJwtTokenService _jwt;
    private readonly IRefreshTokenService _refreshTokens;
    private readonly IAuthAuditLogger _audit;
    private readonly ILoginAttemptProtector _attempts;
    private readonly JwtOptions _jwtOptions;

    public AuthService(AppDbContext db, IPasswordHasher passwordHasher, IJwtTokenService jwt, IRefreshTokenService refreshTokens, IAuthAuditLogger audit, ILoginAttemptProtector attempts, IOptions<JwtOptions> jwtOptions)
    { _db=db; _passwordHasher=passwordHasher; _jwt=jwt; _refreshTokens=refreshTokens; _audit=audit; _attempts=attempts; _jwtOptions=jwtOptions.Value; }

    public async Task<ApiResult<RegisterResponse>> RegisterAsync(RegisterRequest request,CancellationToken cancellationToken=default)
    {
        var errors=ValidateRegister(request);if(errors.Count>0)return ApiResult<RegisterResponse>.Fail(errors[0],400,errors);
        var planName=string.IsNullOrWhiteSpace(request.Plan)?PlanNames.Starter:request.Plan.Trim();if(!string.Equals(planName,PlanNames.Starter,StringComparison.OrdinalIgnoreCase))return ApiResult<RegisterResponse>.Fail("Subscription plan is not currently available.",400);
        if(request.InstallationId==Guid.Empty)return ApiResult<RegisterResponse>.Fail("InstallationId is required.",400);if(string.IsNullOrWhiteSpace(request.DeviceId))return ApiResult<RegisterResponse>.Fail("DeviceId is required.",400);
        var existingInstallation=await _db.ClientInstallations.AsNoTracking().FirstOrDefaultAsync(x=>x.InstallationId==request.InstallationId&&!x.IsDeleted,cancellationToken);
        if(existingInstallation is not null){if(request.ClientUserId is Guid clientUserId&&clientUserId!=Guid.Empty&&existingInstallation.UserId==clientUserId){var sub=await _db.Subscriptions.AsNoTracking().Where(s=>s.CompanyId==existingInstallation.CompanyId&&!s.IsDeleted).OrderByDescending(s=>s.CreatedAt).FirstOrDefaultAsync(cancellationToken);var existingPlan=sub is null?null:await _db.Plans.AsNoTracking().FirstOrDefaultAsync(p=>p.Id==sub.PlanId,cancellationToken);return ApiResult<RegisterResponse>.Ok(new RegisterResponse{Success=true,UserId=existingInstallation.UserId,CompanyId=existingInstallation.CompanyId,SubscriptionId=sub?.Id??Guid.Empty,Plan=existingPlan?.Name??PlanNames.Starter,TrialStartDate=sub?.StartDate??DateTime.UtcNow,TrialEndDate=sub?.EndDate??DateTime.UtcNow});}return ApiResult<RegisterResponse>.Fail("This installation is already registered. Please sign in instead.",409);}
        var email=request.Email.Trim().ToLowerInvariant();var mobile=NormalizeMobile(request.MobileNumber);
        if(request.ClientUserId is Guid existingUserId&&existingUserId!=Guid.Empty){var existingUser=await _db.Users.AsNoTracking().FirstOrDefaultAsync(u=>u.Id==existingUserId&&!u.IsDeleted,cancellationToken);if(existingUser is not null){var membership=await _db.UserCompanies.AsNoTracking().FirstOrDefaultAsync(uc=>uc.UserId==existingUser.Id&&uc.IsActive&&!uc.IsDeleted,cancellationToken);var sub=membership is null?null:await _db.Subscriptions.AsNoTracking().Where(s=>s.CompanyId==membership.CompanyId&&!s.IsDeleted).OrderByDescending(s=>s.CreatedAt).FirstOrDefaultAsync(cancellationToken);return ApiResult<RegisterResponse>.Ok(new RegisterResponse{Success=true,UserId=existingUser.Id,CompanyId=membership?.CompanyId??Guid.Empty,SubscriptionId=sub?.Id??Guid.Empty,Plan=PlanNames.Starter,TrialStartDate=sub?.StartDate??DateTime.UtcNow,TrialEndDate=sub?.EndDate??DateTime.UtcNow});}}
        if(await _db.Users.AnyAsync(u=>u.Email==email&&!u.IsDeleted,cancellationToken))return ApiResult<RegisterResponse>.Fail("Email is already registered.",409);if(await _db.Users.AnyAsync(u=>u.MobileNumber==mobile&&!u.IsDeleted,cancellationToken))return ApiResult<RegisterResponse>.Fail("Mobile number is already registered.",409);
        var plan=await _db.Plans.FirstOrDefaultAsync(p=>p.Name==PlanNames.Starter&&p.IsActive,cancellationToken);if(plan is null||!plan.IsAvailable)return ApiResult<RegisterResponse>.Fail("Subscription plan is not currently available.",400);var ownerRole=await _db.Roles.FirstOrDefaultAsync(r=>r.Name==RoleNames.CompanyOwner&&!r.IsDeleted,cancellationToken);if(ownerRole is null)return ApiResult<RegisterResponse>.Fail("Initial role is not configured.",500);
        await using var tx=await _db.Database.BeginTransactionAsync(cancellationToken);try{var now=DateTime.UtcNow;var userId=request.ClientUserId is Guid uid&&uid!=Guid.Empty?uid:Guid.NewGuid();var companyId=request.ClientCompanyId is Guid cid&&cid!=Guid.Empty?cid:Guid.NewGuid();var membershipId=request.ClientUserCompanyId is Guid ucid&&ucid!=Guid.Empty?ucid:Guid.NewGuid();
            // Codes must remain unique even when several registrations happen within the same second.
            var userCode=$"U{Guid.NewGuid():N}";var companyCode=$"C{Guid.NewGuid():N}";
            var user=new User{Id=userId,UserCode=userCode,FullName=request.FullName.Trim(),Email=email,MobileNumber=mobile,PasswordHash=_passwordHasher.HashPassword(request.Password),IsActiveUser=true,CreatedAt=now,SyncStatus=RecordSyncStatus.Pending};
            var company=new Company{Id=companyId,CompanyCode=companyCode,CompanyName=request.CompanyName.Trim(),OwnerName=string.IsNullOrWhiteSpace(request.OwnerName)?user.FullName:request.OwnerName.Trim(),Email=request.CompanyEmail.Trim().ToLowerInvariant(),MobileNumber=NormalizeMobile(request.CompanyMobile),GSTNumber=request.GstNumber?.Trim()??string.Empty,PANNumber=request.PanNumber?.Trim()??string.Empty,Address=request.CompanyAddress?.Trim()??string.Empty,City=request.CompanyCity?.Trim()??string.Empty,State=request.CompanyState?.Trim()??string.Empty,Country=request.CompanyCountry?.Trim()??string.Empty,PinCode=request.CompanyPinCode?.Trim()??string.Empty,IsActive=true,CreatedAt=now,SyncStatus=RecordSyncStatus.Pending};
            var membership=new UserCompany{Id=membershipId,UserId=user.Id,CompanyId=company.Id,IsOwner=true,IsDefault=true,IsActive=true,CreatedAt=now,SyncStatus=RecordSyncStatus.Pending};var subscription=Subscription.StartFromPlan(company.Id,plan,now,isTrial:true);if(request.ClientSubscriptionId is Guid sid&&sid!=Guid.Empty)subscription.Id=sid;var userRole=new UserRole{Id=Guid.NewGuid(),UserId=user.Id,RoleId=ownerRole.Id,CompanyId=company.Id,CreatedAt=now,SyncStatus=RecordSyncStatus.Pending};var clientInstallation=new ClientInstallation{Id=Guid.NewGuid(),InstallationId=request.InstallationId,DeviceId=request.DeviceId.Trim(),UserId=user.Id,CompanyId=company.Id,RegisteredAt=now,CreatedAt=now,SyncStatus=RecordSyncStatus.Pending};
            _db.Users.Add(user);_db.Companies.Add(company);_db.UserCompanies.Add(membership);_db.Subscriptions.Add(subscription);_db.UserRoles.Add(userRole);_db.ClientInstallations.Add(clientInstallation);await _db.SaveChangesAsync(cancellationToken);await tx.CommitAsync(cancellationToken);return ApiResult<RegisterResponse>.Ok(new RegisterResponse{Success=true,UserId=user.Id,CompanyId=company.Id,SubscriptionId=subscription.Id,Plan=plan.Name,TrialStartDate=subscription.StartDate,TrialEndDate=subscription.EndDate});}catch{await tx.RollbackAsync(cancellationToken);throw;}
    }

    public async Task<ApiResult<LoginResponse>> LoginAsync(LoginRequest request,CancellationToken cancellationToken=default){if(string.IsNullOrWhiteSpace(request.Email)||string.IsNullOrWhiteSpace(request.Password))return ApiResult<LoginResponse>.Fail("Invalid email or password.",401);if(string.IsNullOrWhiteSpace(request.DeviceId))return ApiResult<LoginResponse>.Fail("DeviceId is required.",400);var email=request.Email.Trim().ToLowerInvariant();if(_attempts.IsBlocked(email))return ApiResult<LoginResponse>.Fail("Too many failed login attempts. Please try again later.",429);var user=await _db.Users.AsNoTracking().FirstOrDefaultAsync(u=>u.Email==email&&!u.IsDeleted,cancellationToken);if(user is null||!_passwordHasher.VerifyPassword(request.Password,user.PasswordHash)||!user.IsActiveUser){_attempts.RecordFailure(email);_audit.LoginFailure(email,"invalid_credentials");return ApiResult<LoginResponse>.Fail("Invalid email or password.",401);}var memberships=await _db.UserCompanies.AsNoTracking().Include(uc=>uc.Company).Where(uc=>uc.UserId==user.Id&&uc.IsActive&&!uc.IsDeleted).ToListAsync(cancellationToken);if(memberships.Count==0){_attempts.RecordFailure(email);_audit.LoginFailure(email,"no_company");return ApiResult<LoginResponse>.Fail("Invalid email or password.",401);}UserCompany membership;if(request.CompanyId is Guid requestedCompanyId){membership=memberships.FirstOrDefault(m=>m.CompanyId==requestedCompanyId)!;if(membership is null){_attempts.RecordFailure(email);_audit.LoginFailure(email,"unauthorized_company");return ApiResult<LoginResponse>.Fail("You do not have access to the selected company.",403);}}else membership=memberships.FirstOrDefault(m=>m.IsDefault)??memberships[0];if(membership.Company is null||!membership.Company.IsActive||membership.Company.IsDeleted)return ApiResult<LoginResponse>.Fail("Invalid email or password.",401);var(roles,permissions)=await LoadRolesAndPermissionsAsync(user.Id,membership.CompanyId,cancellationToken);var response=await CreateSessionAndTokensAsync(user,membership,memberships,roles,permissions,request.DeviceId.Trim(),request.DeviceName?.Trim()??string.Empty,request.Platform?.Trim()??string.Empty,cancellationToken);_attempts.Reset(email);_audit.LoginSuccess(user.Id,membership.CompanyId,response.Session.SessionId,request.DeviceId);return ApiResult<LoginResponse>.Ok(response);}

    public async Task<ApiResult<LoginResponse>> RefreshAsync(RefreshRequest request,CancellationToken cancellationToken=default){if(string.IsNullOrWhiteSpace(request.RefreshToken))return ApiResult<LoginResponse>.Fail("Unauthorized.",401);var hash=_refreshTokens.HashRefreshToken(request.RefreshToken);var revokedMatch=await _db.DeviceSessions.FirstOrDefaultAsync(s=>s.RefreshTokenHash==hash&&(!s.IsActive||s.RevokedAt!=null)&&!s.IsDeleted,cancellationToken);if(revokedMatch is not null){await RevokeFamilyAsync(revokedMatch.TokenFamilyId,revokedMatch.UserId,"refresh_reuse",cancellationToken);return ApiResult<LoginResponse>.Fail("Unauthorized.",401);}var session=await _db.DeviceSessions.FirstOrDefaultAsync(s=>s.RefreshTokenHash==hash&&s.IsActive&&s.RevokedAt==null&&!s.IsDeleted,cancellationToken);if(session is null)return ApiResult<LoginResponse>.Fail("Unauthorized.",401);if(request.SessionId is Guid sid&&sid!=session.Id)return ApiResult<LoginResponse>.Fail("Unauthorized.",401);if(!string.IsNullOrWhiteSpace(request.DeviceId)&&!string.Equals(request.DeviceId,session.DeviceId,StringComparison.Ordinal))return ApiResult<LoginResponse>.Fail("Unauthorized.",401);if(session.ExpiresAt<=DateTime.UtcNow){session.IsActive=false;session.RevokedAt=DateTime.UtcNow;await _db.SaveChangesAsync(cancellationToken);return ApiResult<LoginResponse>.Fail("Unauthorized.",401);}var user=await _db.Users.FirstOrDefaultAsync(u=>u.Id==session.UserId&&!u.IsDeleted,cancellationToken);if(user is null||!user.IsActiveUser)return ApiResult<LoginResponse>.Fail("Unauthorized.",401);var membership=await _db.UserCompanies.Include(uc=>uc.Company).FirstOrDefaultAsync(uc=>uc.UserId==user.Id&&uc.CompanyId==session.CompanyId&&uc.IsActive&&!uc.IsDeleted,cancellationToken);if(membership?.Company is null||!membership.Company.IsActive)return ApiResult<LoginResponse>.Fail("Unauthorized.",401);var memberships=await _db.UserCompanies.AsNoTracking().Include(uc=>uc.Company).Where(uc=>uc.UserId==user.Id&&uc.IsActive&&!uc.IsDeleted).ToListAsync(cancellationToken);var(roles,permissions)=await LoadRolesAndPermissionsAsync(user.Id,membership.CompanyId,cancellationToken);var newRefresh=_refreshTokens.GenerateRefreshToken();session.RefreshTokenHash=_refreshTokens.HashRefreshToken(newRefresh);session.LastUsedAt=DateTime.UtcNow;session.UpdatedAt=DateTime.UtcNow;await _db.SaveChangesAsync(cancellationToken);var(accessToken,expiresAt,_)=_jwt.CreateAccessToken(user.Id,membership.CompanyId,session.Id,roles);var response=BuildLoginResponse(user,membership,memberships,roles,permissions,session,accessToken,newRefresh,expiresAt);_audit.TokenRefresh(user.Id,session.Id);return ApiResult<LoginResponse>.Ok(response);}

    public async Task<ApiResult> LogoutAsync(ClaimsPrincipal principal,LogoutRequest request,CancellationToken cancellationToken=default){var userId=TryGetUserId(principal);if(userId is null)return ApiResult.Fail("Unauthorized.",401);DeviceSession? session=null;if(request.SessionId is Guid sid)session=await _db.DeviceSessions.FirstOrDefaultAsync(s=>s.Id==sid&&s.UserId==userId&&!s.IsDeleted,cancellationToken);else if(!string.IsNullOrWhiteSpace(request.RefreshToken)){var hash=_refreshTokens.HashRefreshToken(request.RefreshToken);session=await _db.DeviceSessions.FirstOrDefaultAsync(s=>s.RefreshTokenHash==hash&&s.UserId==userId&&!s.IsDeleted,cancellationToken);}else{var sidClaim=TryGetSessionId(principal);if(sidClaim is not null)session=await _db.DeviceSessions.FirstOrDefaultAsync(s=>s.Id==sidClaim&&s.UserId==userId&&!s.IsDeleted,cancellationToken);}if(session is null)return ApiResult.Ok();session.IsActive=false;session.RevokedAt=DateTime.UtcNow;session.UpdatedAt=DateTime.UtcNow;await _db.SaveChangesAsync(cancellationToken);_audit.Logout(userId.Value,session.Id);return ApiResult.Ok();}

    public async Task<ApiResult<MeResponse>> MeAsync(ClaimsPrincipal principal,CancellationToken cancellationToken=default){var userId=TryGetUserId(principal);var companyId=TryGetCompanyId(principal);if(userId is null||companyId is null)return ApiResult<MeResponse>.Fail("Unauthorized.",401);var user=await _db.Users.AsNoTracking().FirstOrDefaultAsync(u=>u.Id==userId&&!u.IsDeleted&&u.IsActiveUser,cancellationToken);if(user is null)return ApiResult<MeResponse>.Fail("Unauthorized.",401);var membership=await _db.UserCompanies.AsNoTracking().Include(uc=>uc.Company).FirstOrDefaultAsync(uc=>uc.UserId==userId&&uc.CompanyId==companyId&&uc.IsActive&&!uc.IsDeleted,cancellationToken);if(membership?.Company is null)return ApiResult<MeResponse>.Fail("Unauthorized.",401);var memberships=await _db.UserCompanies.AsNoTracking().Include(uc=>uc.Company).Where(uc=>uc.UserId==userId&&uc.IsActive&&!uc.IsDeleted).ToListAsync(cancellationToken);var(roles,permissions)=await LoadRolesAndPermissionsAsync(user.Id,companyId.Value,cancellationToken);return ApiResult<MeResponse>.Ok(new MeResponse{User=new UserDto{Id=user.Id,UserCode=user.UserCode,FullName=user.FullName,Email=user.Email,MobileNumber=user.MobileNumber,UserImg=user.UserImg},Company=MapCompany(membership.Company),Roles=roles.ToList(),Permissions=permissions.ToList(),AvailableCompanies=memberships.Where(m=>m.Company is not null).Select(m=>MapCompany(m.Company!)).ToList()});}

    private async Task<LoginResponse> CreateSessionAndTokensAsync(User user,UserCompany membership,IReadOnlyCollection<UserCompany> memberships,IReadOnlyCollection<string> roles,IReadOnlyCollection<string> permissions,string deviceId,string deviceName,string platform,CancellationToken ct){var now=DateTime.UtcNow;var existing=await _db.DeviceSessions.Where(s=>s.UserId==user.Id&&s.DeviceId==deviceId&&s.IsActive&&s.RevokedAt==null).ToListAsync(ct);foreach(var old in existing){old.IsActive=false;old.RevokedAt=now;old.UpdatedAt=now;}var refresh=_refreshTokens.GenerateRefreshToken();var session=new DeviceSession{Id=Guid.NewGuid(),UserId=user.Id,CompanyId=membership.CompanyId,DeviceId=deviceId,DeviceName=deviceName,Platform=platform,RefreshTokenHash=_refreshTokens.HashRefreshToken(refresh),LastUsedAt=now,ExpiresAt=now.AddDays(_jwtOptions.RefreshTokenDays),IsActive=true,TokenFamilyId=Guid.NewGuid().ToString("N"),CreatedAt=now,SyncStatus=RecordSyncStatus.Synced};_db.DeviceSessions.Add(session);await _db.SaveChangesAsync(ct);var(access,expiresAt,_)=_jwt.CreateAccessToken(user.Id,membership.CompanyId,session.Id,roles);return BuildLoginResponse(user,membership,memberships,roles,permissions,session,access,refresh,expiresAt);}
    private LoginResponse BuildLoginResponse(User user,UserCompany membership,IReadOnlyCollection<UserCompany> memberships,IReadOnlyCollection<string> roles,IReadOnlyCollection<string> permissions,DeviceSession session,string access,string refresh,DateTime expiresAt)=>new(){AccessToken=access,RefreshToken=refresh,AccessTokenExpiresAt=expiresAt,User=new UserDto{Id=user.Id,UserCode=user.UserCode,FullName=user.FullName,Email=user.Email,MobileNumber=user.MobileNumber,UserImg=user.UserImg},Company=MapCompany(membership.Company!),Roles=roles.ToList(),Permissions=permissions.ToList(),AvailableCompanies=memberships.Where(m=>m.Company is not null).Select(m=>MapCompany(m.Company!)).ToList(),Session=new SessionDto{SessionId=session.Id,DeviceId=session.DeviceId,DeviceName=session.DeviceName,Platform=session.Platform,LastUsedAt=session.LastUsedAt,ExpiresAt=session.ExpiresAt}};
    private async Task<(IReadOnlyCollection<string> Roles,IReadOnlyCollection<string> Permissions)> LoadRolesAndPermissionsAsync(Guid userId,Guid companyId,CancellationToken ct){var roleIds=await _db.UserRoles.AsNoTracking().Where(ur=>ur.UserId==userId&&!ur.IsDeleted&&(ur.CompanyId==null||ur.CompanyId==companyId)).Select(ur=>ur.RoleId).Distinct().ToListAsync(ct);var roles=await _db.Roles.AsNoTracking().Where(r=>roleIds.Contains(r.Id)&&!r.IsDeleted).Select(r=>r.Name).ToListAsync(ct);var permissions=await _db.RolePermissions.AsNoTracking().Where(rp=>roleIds.Contains(rp.RoleId)&&!rp.IsDeleted&&!rp.Permission.IsDeleted).Select(rp=>rp.Permission.PermissionName).Distinct().OrderBy(x=>x).ToListAsync(ct);return(roles,permissions);}
    private async Task RevokeFamilyAsync(string? familyId,Guid userId,string reason,CancellationToken ct){if(string.IsNullOrWhiteSpace(familyId))return;var now=DateTime.UtcNow;var sessions=await _db.DeviceSessions.Where(s=>s.UserId==userId&&s.TokenFamilyId==familyId&&s.IsActive).ToListAsync(ct);foreach(var s in sessions){s.IsActive=false;s.RevokedAt=now;s.UpdatedAt=now;}if(sessions.Count>0)await _db.SaveChangesAsync(ct);_audit.RefreshReuse(userId,familyId,reason);}
    private static List<string> ValidateRegister(RegisterRequest r){var errors=new List<string>();if(string.IsNullOrWhiteSpace(r.FullName))errors.Add("Full name is required.");if(string.IsNullOrWhiteSpace(r.Email)||!r.Email.Contains('@'))errors.Add("Valid email is required.");if(string.IsNullOrWhiteSpace(r.MobileNumber))errors.Add("Mobile number is required.");if(string.IsNullOrWhiteSpace(r.Password)||r.Password.Length<8)errors.Add("Password must be at least 8 characters.");if(r.Password!=r.ConfirmPassword)errors.Add("Passwords do not match.");if(string.IsNullOrWhiteSpace(r.CompanyName))errors.Add("Company name is required.");if(string.IsNullOrWhiteSpace(r.CompanyEmail)||!r.CompanyEmail.Contains('@'))errors.Add("Valid company email is required.");if(string.IsNullOrWhiteSpace(r.CompanyMobile))errors.Add("Company mobile is required.");return errors;}
    private static string NormalizeMobile(string? value)=>new((value??string.Empty).Where(char.IsDigit).ToArray());private static Guid? TryGetUserId(ClaimsPrincipal p)=>Guid.TryParse(p.FindFirstValue(ClaimTypes.NameIdentifier)??p.FindFirstValue("sub"),out var id)?id:null;private static Guid? TryGetCompanyId(ClaimsPrincipal p)=>Guid.TryParse(p.FindFirstValue("company_id"),out var id)?id:null;private static Guid? TryGetSessionId(ClaimsPrincipal p)=>Guid.TryParse(p.FindFirstValue("session_id"),out var id)?id:null;private static CompanyDto MapCompany(Company c)=>new(){Id=c.Id,CompanyCode=c.CompanyCode,CompanyName=c.CompanyName,Email=c.Email,MobileNumber=c.MobileNumber,IsActive=c.IsActive};
}