using AveroNova.App.UI.Models;
using AveroNova.App.UI.Navigation;
using AveroNova.App.UI.Services.Interfaces;
using Microsoft.Maui.Controls.Shapes;

namespace AveroNova.App.UI.Pages.Subscription;

public partial class SubscriptionPage:ContentPage,IHostedPage
{
 private readonly ISubscriptionService _service;private readonly ICompanyService _company;private SubscriptionModel? _current;
 public SubscriptionPage(ISubscriptionService service,ICompanyService company){InitializeComponent();_service=service;_company=company;}
 protected override async void OnAppearing(){base.OnAppearing();await LoadForHostAsync();}
 public async Task LoadForHostAsync(){var cid=_company.CurrentCompany?.LocalId??Guid.Empty;_current=await _service.GetCurrentAsync(cid);var plans=await _service.GetPlansAsync();var payments=await _service.GetPaymentHistoryAsync(cid);Build(plans,payments);}
 private async void OnRefreshing(object s,EventArgs e){await LoadForHostAsync();Refresher.IsRefreshing=false;}
 private void Build(List<SubscriptionPlanModel> plans,List<SubscriptionPaymentModel> payments){SubscriptionContent.Children.Clear();SubscriptionContent.MaximumWidthRequest=900;SubscriptionContent.HorizontalOptions=LayoutOptions.Center;
  var current=new VerticalStackLayout{Spacing=10};current.Children.Add(Title("Current Plan"));current.Children.Add(new Label{Text=_current?.PlanName??"No subscription",FontSize=22,FontAttributes=FontAttributes.Bold});if(_current is not null){current.Children.Add(new Label{Text=$"₹{_current.Price:N2} • {_current.BillingLabel} • {_current.StatusLabel}",TextColor=Color.FromArgb("#2563EB"),FontAttributes=FontAttributes.Bold});current.Children.Add(new Label{Text=$"Valid until {_current.ExpiryDate:dd MMM yyyy} • {_current.DaysRemaining} days remaining"});current.Children.Add(new Label{Text=$"Limits: {_current.MaxUsers} users • {_current.MaxCompanies} companies • {_current.MaxStorageMB} MB"});var cancel=new Button{Text="Cancel Subscription",Style=(Style)Resources["DangerButton"],IsEnabled=_current.Status!=SubscriptionStatus.Cancelled};cancel.Clicked+=OnCancelClicked;current.Children.Add(cancel);}SubscriptionContent.Children.Add(Card(current));
  SubscriptionContent.Children.Add(Title("Available Plans"));foreach(var plan in plans){var s=new VerticalStackLayout{Spacing=8};s.Children.Add(new Label{Text=$"{plan.Name}{(plan.IsPopular?" • Popular":"")}",FontSize=18,FontAttributes=FontAttributes.Bold});s.Children.Add(new Label{Text=plan.Description,TextColor=Color.FromArgb("#64748B")});s.Children.Add(new Label{Text=$"₹{plan.MonthlyPrice:N0}/month  •  ₹{plan.YearlyPrice:N0}/year",HorizontalTextAlignment=TextAlignment.Center,FontAttributes=FontAttributes.Bold});s.Children.Add(new Label{Text=string.Join("  •  ",plan.Features),HorizontalTextAlignment=TextAlignment.Center,LineBreakMode=LineBreakMode.WordWrap});var buttons=new Grid{ColumnDefinitions=new ColumnDefinitionCollection(new ColumnDefinition(GridLength.Star),new ColumnDefinition(GridLength.Star)),ColumnSpacing=8};var monthly=new Button{Text=plan.IsCurrentPlan?"Current Monthly":"Choose Monthly",Style=(Style)Resources["SecondaryButton"],IsEnabled=plan.IsAvailable&&!plan.IsCurrentPlan};var yearly=new Button{Text=plan.IsCurrentPlan?"Switch to Yearly":"Choose Yearly",Style=(Style)Resources["PrimaryButton"],IsEnabled=plan.IsAvailable};monthly.Clicked+=async(_,_)=>await ChangePlanAsync(plan.Id,BillingCycle.Monthly);yearly.Clicked+=async(_,_)=>await ChangePlanAsync(plan.Id,BillingCycle.Yearly);buttons.Add(monthly);buttons.Add(yearly,1,0);s.Children.Add(buttons);SubscriptionContent.Children.Add(Card(s));}
  SubscriptionContent.Children.Add(Title("Payment History"));if(payments.Count==0)SubscriptionContent.Children.Add(new Label{Text="No subscription payments yet.",HorizontalTextAlignment=TextAlignment.Center,Margin=new Thickness(0,20)});foreach(var p in payments){var g=new Grid{ColumnDefinitions=new ColumnDefinitionCollection(new ColumnDefinition(GridLength.Star),new ColumnDefinition(GridLength.Auto)),ColumnSpacing=12};var info=new VerticalStackLayout{Spacing=2};info.Children.Add(new Label{Text=$"{p.PaymentNumber} • {p.PlanName}",FontAttributes=FontAttributes.Bold});info.Children.Add(new Label{Text=$"{p.PaymentDate:dd MMM yyyy} • {p.Method} • {p.Status}",FontSize=12,TextColor=Color.FromArgb("#64748B")});g.Add(info);g.Add(new Label{Text=$"₹{p.Amount:N2}",FontAttributes=FontAttributes.Bold,VerticalOptions=LayoutOptions.Center},1,0);SubscriptionContent.Children.Add(Card(g));}
 }
 private async Task ChangePlanAsync(string planId,BillingCycle cycle){var cid=_company.CurrentCompany?.LocalId??Guid.Empty;var result=await _service.UpgradeAsync(cid,planId,cycle);await DisplayAlert(result.Ok?"Saved":"Unable to change plan",result.Ok?"Plan change saved offline and queued for synchronization.":result.Error??"Request failed.","OK");if(result.Ok)await LoadForHostAsync();}
 private async void OnCancelClicked(object? s,EventArgs e){if(!await DisplayAlert("Cancel subscription","Disable this subscription and auto-renewal?","Cancel Plan","Keep Plan"))return;var result=await _service.CancelAsync(_company.CurrentCompany?.LocalId??Guid.Empty);await DisplayAlert(result.Ok?"Cancelled":"Unable to cancel",result.Ok?"Cancellation saved and queued for synchronization.":result.Error??"Request failed.","OK");if(result.Ok)await LoadForHostAsync();}
 private static Label Title(string text)=>new(){Text=text,FontSize=16,FontAttributes=FontAttributes.Bold,HorizontalTextAlignment=TextAlignment.Center,Margin=new Thickness(0,8)};
 private Border Card(View content)=>new(){Content=content,Style=(Style)Resources["AppCard"],HorizontalOptions=LayoutOptions.Fill};
}
